version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 437952802943.dkr.ecr.us-east-1.amazonaws.com
      - REPO_URI=437952802943.dkr.ecr.us-east-1.amazonaws.com/dockerapplication

  build:
    commands:
      - mvn clean package -DskipTests
      - docker build -t dockerapplication .
      - docker tag dockerapplication:latest $REPO_URI:latest

  post_build:
    commands:
      - docker push $REPO_URI:latest